<b>Transpose</b>

A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped.

This is denoted by the superscript “T” next to the matrix.

C = A^T

We can transpose a matrix in NumPy by calling the T attribute.

In [3]:
# transpose matrix
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
print("\n")
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]


[[1 3 5]
 [2 4 6]]


<b>Inversion</b>

The operation of inverting a matrix is indicated by a -1 superscript next to the matrix; for example, A^-1. The result of the operation is referred to as the inverse of the original matrix; for example, B is the inverse of A.

B = A^-1

Not all matrices are invertible.

A matrix can be inverted in NumPy using the inv() function.

In [5]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([[1.0, 2.0], [3.0, 4.0]])
print(A)
print("\n")
# invert matrix
B = inv(A)
print(B)

[[1. 2.]
 [3. 4.]]


[[-2.   1. ]
 [ 1.5 -0.5]]


<b>Square Matrix</b>

A square matrix is a matrix where the number of rows (n) equals the number of columns (m).

n = m

The square matrix is contrasted with the rectangular matrix where the number of rows and columns are not equal.

<b>Symmetric Matrix</b>

A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle.

To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the top left to the bottom right.

A symmetric matrix is always square and equal to its own transpose.

M = M^T

<b>Triangular Matrix</b>

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values.

A triangular matrix with values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular matrix with values only below the main diagonal is called a lower triangular matrix.

<b>Diagonal Matrix</b>

A diagonal matrix is one where values outside of the main diagonal have a zero value, where the main diagonal is taken from the top left of the matrix to the bottom right.

A diagonal matrix is often denoted with the variable D and may be represented as a full matrix or as a vector of values on the main diagonal.


Reference: https://machinelearningmastery.com/linear_algebra_for_machine_learning/