<b>What is a Vector? </b>

A vector is a tuple of one or more values called scalars.

Vectors are often represented using a lowercase character such as "v"; for example:

v = (v1, v2, v3)

Where v1, v2, v3 are scalar values, often real values.​

</b>Defining a Vector</b>
We can represent a vector in Python as a NumPy array.

A NumPy array can be created from a list of numbers. For example, below we define a vector with the length of 3 and the integer values 1, 2 and 3.

# create a vector
  

In [2]:
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


<b>Vector Multiplication</b>
Two vectors of equal length can be multiplied together.
c = a * b
As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length.
a * b = (a1 * b1, a2 * b2, a3 * b3)
We can perform this operation directly in NumPy.

# multiply vectors

In [3]:
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


Reference: https://machinelearningmastery.com/linear_algebra_for_machine_learning/